all:  null.o chap14_q4.o chap14_q5.o chap14_q6.o chap14_q7.o

null.o: null.c
	gcc -g null.c -o null.o

chap14_q4.o: chap14_q4.c
	gcc -g chap14_q4.c -o chap14_q4.o

chap14_q5.o: chap14_q5.c
	gcc -g chap14_q5.c -o chap14_q5.o

chap14_q6.o: chap14_q6.c
	gcc -g chap14_q6.c -o chap14_q6.o

chap14_q7.o: chap14_q7.c
	gcc -g chap14_q7.c -o chap14_q7.o


clean: 
	rm *.o 
