
all: chap6_q1.o chap6_q2.o chap6_q3.o

hap6_q1.o: chap6_q1.c
	gcc chap6_q1.c -o chap6_q1.o

chap6_q2.o: chap6_q2.c
	gcc chap6_q2.c -o chap6_q2.o

chap6_q3.o: chap6_q3.c
	gcc chap6_q3.c -o chap6_q3.o

clean: 
	rm *.o 
