
all: chap5_q1.o chap5_q2.o chap5_q4.o chap5_q7.o chap5_q8.o

chap5_q1.o: chap5_q1.c
	gcc chap5_q1.c -o chap5_q1.o

chap5_q2.o: chap5_q2.c
	gcc chap5_q2.c -o chap5_q2.o

chap5_q4.o: chap5_q4.c
	gcc chap5_q4.c -o chap5_q4.o

chap5_q7.o: chap5_q7.c
	gcc chap5_q7.c -o chap5_q7.o

chap5_q8.o: chap5_q8.c
	gcc chap5_q8.c -o chap5_q8.o

clean: 
	rm *.o 
